### ISSUE TITLE
Метод разбора новостей

### ISSUE THREAD

**Issue by opennet** [nvb13/OpenNet_to_xmpp#1]
Разбор  HTML по class=title2 не совсем верный путь, не факт, что разметка сохранится. 
Лучше разбирать RSS или уже распарсенные варианты экспорта (http://wiki.opennet.ru/RSS) и вариант в UTF8 (https://www.opennet.ru/opennews/opennews_all_utf.rss)
Например, http://www.opennet.ru/opennews/opennews_1.txt или http://www.opennet.ru/opennews/opennews_2.txt

**Comment by nvb13** [comment]
Спасибо, сделаю.
